export type Mlpconfig = {
    "dao_name": string,
    "member_principal": string,
    "token_supply": number,
    "token_decimals": number,
    "token_fee": number,
    "token_2": string,
    "token_name": string,
    "token_symbol": string,
    "proposal_cost":number,
    "stake_time":number,
    "clif":number,
    "vested":number,
    "interval":number,
    "total_allocation":number,
    "funding_goal":number,
    "swap_fee":number,
    "swap_funders_fee":number,
}